name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v3
        with:
          subjectPattern: '^\[PASSPORTS-[0-9]+\] - .*'
